import { prisma } from './prisma';

const PREFIXES = {
  USR: 'RUPSA-USR',
  SCH: 'RUPSA-SCH',
  STD: 'RUPSA-STD',
  GRD: 'RUPSA-GRD',
  REG: 'RUPSA-REG',
  INV: 'RUPSA-INV',
  PAY: 'RUPSA-PAY',
  RCT: 'RUPSA-RCT',
  SET: 'RUPSA-SET',
  REC: 'RUPSA-REC',
  LA: 'RUPSA-LA',
  LOAN: 'RUPSA-LOAN',
  REP: 'RUPSA-REP',
  DISB: 'RUPSA-DISB',
  ASSESS: 'ASSESS',
  GUA: 'RUPSA-GUA',
  CLM: 'RUPSA-CLM',
  CON: 'RUPSA-CON',
  KYC: 'RUPSA-KYC',
  NTF: 'RUPSA-NTF',
  MBA: 'RUPSA-MBA',
  MAD: 'RUPSA-MAD',
  FI: 'FI',
  REQ: 'REQ',
  DNR: 'RUPSA-DNR',
  CMP: 'RUPSA-CMP',
  PLG: 'RUPSA-PLG',
  DON: 'RUPSA-DON',
  DPY: 'RUPSA-DPY',
  BNF: 'RUPSA-BNF',
  ALC: 'RUPSA-ALC',
  DST: 'RUPSA-DST',
  DBS: 'RUPSA-DBS',
  DRF: 'RUPSA-DRF',
  ADJ: 'RUPSA-ADJ',
  DRC: 'RUPSA-DRC',
  AGR: 'RUPSA-AGR',
  IMP: 'RUPSA-IMP',
  DAU: 'RUPSA-DAU',
  DRL: 'RUPSA-DRL',
  MSG: 'RUPSA-MSG',
  DCM: 'RUPSA-DCM',
  INK: 'RUPSA-INK',
  IOP: 'RUPSA-IOP',
  IAP: 'RUPSA-IAP',
  IVT: 'RUPSA-IVT',
  ICT: 'RUPSA-ICT',
  IRT: 'RUPSA-IRT',
  IXT: 'RUPSA-IXT',
  ITR: 'RUPSA-ITR',
  IAU: 'RUPSA-IAU',
  IMS: 'RUPSA-IMS',
  ACC: 'RUPSA-ACC',
  AAU: 'RUPSA-AAU',
  AMS: 'RUPSA-AMS',
  LPR: 'RUPSA-LPR',
  LCR: 'RUPSA-LCR',
  LLN: 'RUPSA-LLN',
  LEN: 'RUPSA-LEN',
  LSS: 'RUPSA-LSS',
  LAT: 'RUPSA-LAT',
  LTR: 'RUPSA-LTR',
  LAS: 'RUPSA-LAS',
  LCF: 'RUPSA-LCF',
  LRT: 'RUPSA-LRT',
  LGL: 'RUPSA-LGL',
  LHV: 'RUPSA-LHV',
  LEV: 'RUPSA-LEV',
  LFR: 'RUPSA-LFR',
  LFB: 'RUPSA-LFB',
  LAU: 'RUPSA-LAU',
  LMS: 'RUPSA-LMS',
  EGR: 'RUPSA-EGR',
  EGM: 'RUPSA-EGM',
  ESC: 'RUPSA-ESC',
  EAG: 'RUPSA-EAG',
  ECN: 'RUPSA-ECN',
  EGC: 'RUPSA-EGC',
  EAL: 'RUPSA-EAL',
  ETX: 'RUPSA-ETX',
  EFZ: 'RUPSA-EFZ',
  ERL: 'RUPSA-ERL',
  EWD: 'RUPSA-EWD',
  ERF: 'RUPSA-ERF',
  ECL: 'RUPSA-ECL',
  CPL: 'RUPSA-CPL',
  COL: 'RUPSA-COL',
  CVL: 'RUPSA-CVL',
  CVF: 'RUPSA-CVF',
  CLI: 'RUPSA-CLI',
  CXR: 'RUPSA-CXR',
  CSU: 'RUPSA-CSU',
  CWM: 'RUPSA-CWM',
  CRZ: 'RUPSA-CRZ',
  CEN: 'RUPSA-CEN',
  SFC: 'RUPSA-SFC',
  SGA: 'RUPSA-SGA',
  SEL: 'RUPSA-SEL',
  SAS: 'RUPSA-SAS',
  SDC: 'RUPSA-SDC',
  SGT: 'RUPSA-SGT',
  SCT: 'RUPSA-SCT',
  SFE: 'RUPSA-SFE',
  SRN: 'RUPSA-SRN',
  SAM: 'RUPSA-SAM',
  SCL: 'RUPSA-SCL',
  SCP: 'RUPSA-SCP',
  SRC: 'RUPSA-SRC',
  SRA: 'RUPSA-SRA',
  SCX: 'RUPSA-SCX',
  SLK: 'RUPSA-SLK',
  SDF: 'RUPSA-SDF',
  ESO: 'RUPSA-ESO',
  SRE: 'RUPSA-SRE',
  SDO: 'RUPSA-SDO',
  SAW: 'RUPSA-SAW',
  SAU: 'RUPSA-SAU',
  SNT: 'RUPSA-SNT',
  MEM: 'RUPSA-MEM',
  MBR: 'RUPSA-MBR',
  MCA: 'RUPSA-MCA',
  MRQ: 'RUPSA-MRQ',
  MAP: 'RUPSA-MAP',
  MDC: 'RUPSA-MDC',
  MVF: 'RUPSA-MVF',
  MDS: 'RUPSA-MDS',
  MFE: 'RUPSA-MFE',
  MPY: 'RUPSA-MPY',
  MCF: 'RUPSA-MCF',
  MRN: 'RUPSA-MRN',
  MCH: 'RUPSA-MCH',
  MSP: 'RUPSA-MSP',
  MRA: 'RUPSA-MRA',
  MTM: 'RUPSA-MTM',
  MNT: 'RUPSA-MNT',
  MAU: 'RUPSA-MAU',
  LPD: 'RUPSA-LPD',
  LCS: 'RUPSA-LCS',
  LDC: 'RUPSA-LDC',
  LKY: 'RUPSA-LKY',
  LCN: 'RUPSA-LCN',
  LCA: 'RUPSA-LCA',
  LOF: 'RUPSA-LOF',
  LCT: 'RUPSA-LCT',
  LCL: 'RUPSA-LCL',
  LGQ: 'RUPSA-LGQ',
  LIN: 'RUPSA-LIN',
  LCO: 'RUPSA-LCO',
  LPM: 'RUPSA-LPM',
  LRV: 'RUPSA-LRV',
  LWO: 'RUPSA-LWO',
  LRS: 'RUPSA-LRS',
  LHD: 'RUPSA-LHD',
  LTP: 'RUPSA-LTP',
  LRF: 'RUPSA-LRF',
  LXF: 'RUPSA-LXF',
  LAD: 'RUPSA-LAD',
  LRD: 'RUPSA-LRD',
  LST: 'RUPSA-LST',
  LNT: 'RUPSA-LNT',
  LNA: 'RUPSA-LNA',
} as const;

export type IdKind = keyof typeof PREFIXES;

export async function nextPublicId(kind: IdKind): Promise<string> {
  const prefix = PREFIXES[kind];
  const row = await prisma.idSequence.upsert({
    where: { prefix },
    create: { prefix, value: 1 },
    update: { value: { increment: 1 } },
  });
  return `${prefix}-${String(row.value).padStart(6, '0')}`;
}

export function newRequestId(): string {
  return `REQ-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`.toUpperCase();
}
