export type HttpMethod = 'GET' | 'POST' | 'PATCH'

export type Field = {
  name: string
  example: string
  description: string
}

export type Endpoint = {
  id: string
  group: string
  method: HttpMethod
  path: string
  title: string
  description: string
  auth: boolean
  permission?: string
  idempotent?: boolean
  pathParams?: Field[]
  queryParams?: Field[]
  body?: string
}

export const API_GROUPS = [
  'Health',
  'Auth',
  'Schools',
  'Guardians',
  'Family',
  'Students',
  'Institutions',
  'Invoices',
  'Payments',
  'Webhooks',
  'Settlements',
  'Reconciliation',
  'Consents',
  'Loans',
  'Guarantees',
  'Notifications',
  'Reports',
  'Donations',
  'Investments',
  'Accounts',
  'Financial literacy',
] as const

export const SEEDED_ACCOUNTS = [
  { label: 'Admin', email: 'admin@rupsanext.rw', password: 'ChangeMe123!', role: 'SYSTEM_ADMINISTRATOR' },
  { label: 'School', email: 'finance@example.rw', password: 'ChangeMe123!', role: 'SCHOOL_USER' },
  { label: 'Bank', email: 'credit@bank.rw', password: 'ChangeMe123!', role: 'BANK_USER' },
  { label: 'Parent', email: 'parent@example.rw', password: 'ChangeMe123!', role: 'PARENT' },
] as const

export const endpoints: Endpoint[] = [
  {
    id: 'health',
    group: 'Health',
    method: 'GET',
    path: '/health',
    title: 'Service health',
    description: 'Liveness check for the API process. No authentication.',
    auth: false,
  },
  {
    id: 'auth-login',
    group: 'Auth',
    method: 'POST',
    path: '/api/v1/auth/login',
    title: 'Login',
    description: 'Exchange email and password for a Bearer access token and refresh token.',
    auth: false,
    body: JSON.stringify({
      email: 'admin@rupsanext.rw',
      password: 'ChangeMe123!',
    }, null, 2),
  },
  {
    id: 'auth-register',
    group: 'Auth',
    method: 'POST',
    path: '/api/v1/auth/register',
    title: 'Register',
    description: 'Open a parent account. The parent must give parental-responsibility consent before children\'s records can be processed.',
    auth: false,
    body: JSON.stringify({
      email: 'parent@example.rw',
      password: 'ChangeMe123!',
      fullName: 'Parent Guardian',
      phone: '+250788000004',
      parentalConsent: true,
    }, null, 2),
  },
  {
    id: 'auth-me',
    group: 'Auth',
    method: 'GET',
    path: '/api/v1/auth/me',
    title: 'Current session',
    description: 'Return the authenticated actor, role and permission set.',
    auth: true,
  },
  {
    id: 'school-applications-create',
    group: 'Schools',
    method: 'POST',
    path: '/api/v1/school-applications',
    title: 'Public school application',
    description: 'Submit a complete member-school application without a workspace account. The file arrives as SUBMITTED, with registration verification pending.',
    auth: false,
    body: JSON.stringify({
      schoolName: 'Kigali Heights Academy',
      registrationNumber: 'SCH-67890',
      schoolType: 'COMBINED',
      ownershipType: 'PRIVATE',
      dateEstablished: '2012-09-01',
      operatingStatus: 'OPERATING',
      studentCount: 640,
      teacherCount: 42,
      phone: '+250788000200',
      email: 'office@heights.rw',
      address: {
        province: 'Kigali City',
        district: 'Kicukiro',
        sector: 'Niboye',
        cell: 'Gatare',
        village: 'Gatare',
        physicalAddress: 'KK 15 Ave',
      },
      taxIdentificationNumber: '123456789',
      registrationCertificateNumber: 'RDB-67890',
      registrationDate: '2012-09-01',
      registrationAuthority: 'Rwanda Development Board',
      licenseNumber: 'MINEDUC-67890',
      licenseExpiryDate: '2027-09-01',
      legalStatus: 'LICENSED',
      representative: {
        fullName: 'Jean Habimana',
        position: 'Director',
        nationalId: '1197080012345678',
        phone: '+250788000201',
        email: 'director@heights.rw',
        appointmentDate: '2018-01-15',
      },
      bankAccount: {
        bankName: 'Bank of Kigali',
        branch: 'Kicukiro',
        accountName: 'Kigali Heights Academy',
        accountNumber: '000123456789',
        currency: 'RWF',
      },
      documents: [
        { documentType: 'REGISTRATION_CERTIFICATE', fileName: 'rdb-registration.pdf' },
        { documentType: 'LICENSE', fileName: 'operating-licence.pdf' },
        { documentType: 'AUTHORIZATION_LETTER', fileName: 'authorization.pdf' },
        { documentType: 'ID_DOCUMENT', fileName: 'director-id.pdf' },
        { documentType: 'BANK_LETTER', fileName: 'bank-letter.pdf' },
      ],
    }, null, 2),
  },
  {
    id: 'membership-applications-create',
    group: 'Schools',
    method: 'POST',
    path: '/api/v1/membership-applications',
    title: 'Become a UPSA member',
    description: 'Submit a public UPSA membership request with the same registration details as the officer form, including the required documents. A confirmation email is sent to the contact address.',
    auth: false,
    body: JSON.stringify({
      schoolName: 'Kigali Heights Academy',
      registrationNumber: 'SCH-44001',
      categoryCode: 'FULL',
      institutionType: 'SECONDARY',
      contactName: 'Claudine Uwimana',
      title: 'Head teacher',
      phone: '+250788000200',
      email: 'office@heights.rw',
      registrationCertificateNumber: 'RDB-44001',
      representativePhone: '+250788000200',
      representativeEmail: 'head@heights.rw',
      address: { province: 'City Of Kigali', district: 'Kicukiro', sector: 'Niboye', cell: 'Gatare', physicalAddress: 'KK 12 Ave' },
      documents: [{ documentType: 'REGISTRATION_CERTIFICATE', fileName: 'registration.pdf', uploadId: 'abc.pdf' }],
    }, null, 2),
  },
  {
    id: 'schools-list',
    group: 'Schools',
    method: 'GET',
    path: '/api/v1/schools',
    title: 'List schools',
    description: 'List member schools. Filter by lifecycle status when needed.',
    auth: true,
    permission: 'school.read',
    queryParams: [{ name: 'status', example: 'ACTIVE', description: 'Optional SchoolStatus filter' }],
  },
  {
    id: 'schools-get',
    group: 'Schools',
    method: 'GET',
    path: '/api/v1/schools/:schoolId',
    title: 'Retrieve school',
    description: 'Get a school by public identifier.',
    auth: true,
    permission: 'school.read',
    pathParams: [{ name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'Public school ID' }],
  },
  {
    id: 'schools-create',
    group: 'Schools',
    method: 'POST',
    path: '/api/v1/schools',
    title: 'Create school',
    description: 'Start a member-school application. Initial status is APPLICATION.',
    auth: true,
    permission: 'school.write',
    body: JSON.stringify({
      rupsaMemberId: 'RUPSA-MEM-000124',
      schoolName: 'Kigali Heights Academy',
      registrationNumber: 'SCH-67890',
      taxIdentificationNumber: 'TIN-100200',
      phone: '+250788000200',
      email: 'office@heights.rw',
      address: { province: 'Kigali', district: 'Kicukiro' },
    }, null, 2),
  },
  {
    id: 'schools-update',
    group: 'Schools',
    method: 'PATCH',
    path: '/api/v1/schools/:schoolId',
    title: 'Update school',
    description: 'Patch school profile or move it through the verification lifecycle.',
    auth: true,
    permission: 'school.write',
    pathParams: [{ name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'Public school ID' }],
    body: JSON.stringify({ status: 'ACTIVE', phone: '+250788000100' }, null, 2),
  },
  {
    id: 'schools-profile',
    group: 'Schools',
    method: 'GET',
    path: '/api/v1/schools/:schoolId/financial-profile',
    title: 'Financial profile',
    description: 'Verified or derived collections, student count and existing loan exposure. Filter by consent in production.',
    auth: true,
    permission: 'school.read',
    pathParams: [{ name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'Public school ID' }],
  },
  {
    id: 'guardians-create',
    group: 'Guardians',
    method: 'POST',
    path: '/api/v1/guardians',
    title: 'Create guardian',
    description: 'Create a parent or guardian identity that can be linked to students.',
    auth: true,
    permission: 'student.write',
    body: JSON.stringify({
      fullName: 'Claudine Uwase',
      phone: '+250788000011',
      email: 'claudine@example.rw',
    }, null, 2),
  },
  {
    id: 'guardians-list',
    group: 'Guardians',
    method: 'GET',
    path: '/api/v1/guardians',
    title: 'List guardians',
    description: 'List guardian records.',
    auth: true,
    permission: 'student.read',
  },
  {
    id: 'guardians-get',
    group: 'Guardians',
    method: 'GET',
    path: '/api/v1/guardians/:guardianId',
    title: 'Retrieve guardian',
    description: 'Get a guardian by public identifier.',
    auth: true,
    permission: 'student.read',
    pathParams: [{ name: 'guardianId', example: 'RUPSA-GRD-000123', description: 'Public guardian ID' }],
  },
  {
    id: 'family-home',
    group: 'Family',
    method: 'GET',
    path: '/api/v1/family',
    title: 'Guardian family',
    description: 'Parent home: contact, identity, parental authorization, linked schools, payment preferences, notices, and — once consent is active — students, outstanding fees, payment history, and digital receipts.',
    auth: true,
  },
  {
    id: 'students-create',
    group: 'Students',
    method: 'POST',
    path: '/api/v1/students',
    title: 'Create student',
    description: 'Create a student under a school and optionally attach a primary guardian.',
    auth: true,
    permission: 'student.write',
    body: JSON.stringify({
      schoolId: 'RUPSA-SCH-000123',
      studentExternalId: 'STU-10002',
      studentName: 'Aline Mukamana',
      academicYear: '2026',
      classLevel: 'S2',
      guardianId: 'RUPSA-GRD-000123',
      feeCategory: 'DAY',
    }, null, 2),
  },
  {
    id: 'students-list',
    group: 'Students',
    method: 'GET',
    path: '/api/v1/students',
    title: 'List students',
    description: 'List students, optionally scoped to one school. A parent account only receives students linked to their guardian.',
    auth: true,
    permission: 'student.read',
    queryParams: [{ name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'Optional school filter' }],
  },
  {
    id: 'students-get',
    group: 'Students',
    method: 'GET',
    path: '/api/v1/students/:studentId',
    title: 'Retrieve student',
    description: 'Get a student identity and school relationship.',
    auth: true,
    permission: 'student.read',
    pathParams: [{ name: 'studentId', example: 'RUPSA-STD-000123', description: 'Public student ID' }],
  },
  {
    id: 'students-summary',
    group: 'Students',
    method: 'GET',
    path: '/api/v1/students/:studentId/financial-summary',
    title: 'Student financial summary',
    description: 'Authoritative billed, paid and outstanding balances from the school ledger.',
    auth: true,
    permission: 'student.read',
    pathParams: [{ name: 'studentId', example: 'RUPSA-STD-000123', description: 'Public student ID' }],
  },
  {
    id: 'institutions-list',
    group: 'Institutions',
    method: 'GET',
    path: '/api/v1/institutions',
    title: 'List institutions',
    description: 'Banks, MFIs and PSPs that hold an integration profile.',
    auth: true,
    permission: 'loan.read',
  },
  {
    id: 'invoices-create',
    group: 'Invoices',
    method: 'POST',
    path: '/api/v1/invoices',
    title: 'Create invoice',
    description: 'The ledger is the record of what is owed. Payments only record how money arrived.',
    auth: true,
    permission: 'invoice.write',
    body: JSON.stringify({
      schoolId: 'RUPSA-SCH-000123',
      studentId: 'RUPSA-STD-000123',
      currency: 'RWF',
      amount: 300000,
      description: 'Term 3 School Fees',
      dueDate: '2026-10-15',
    }, null, 2),
  },
  {
    id: 'invoices-list',
    group: 'Invoices',
    method: 'GET',
    path: '/api/v1/invoices',
    title: 'List invoices',
    description: 'Filter the school ledger by school, student or status.',
    auth: true,
    permission: 'invoice.read',
    queryParams: [
      { name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'School filter' },
      { name: 'studentId', example: 'RUPSA-STD-000123', description: 'Student filter' },
      { name: 'status', example: 'PARTIALLY_PAID', description: 'Invoice status' },
    ],
  },
  {
    id: 'invoices-get',
    group: 'Invoices',
    method: 'GET',
    path: '/api/v1/invoices/:invoiceId',
    title: 'Retrieve invoice',
    description: 'Amount, amount paid, remaining balance and status.',
    auth: true,
    permission: 'invoice.read',
    pathParams: [{ name: 'invoiceId', example: 'RUPSA-INV-000457', description: 'Public invoice ID' }],
  },
  {
    id: 'payments-create',
    group: 'Payments',
    method: 'POST',
    path: '/api/v1/payments',
    title: 'Initiate payment',
    description: 'Start payment orchestration on an approved rail. Requires Idempotency-Key.',
    auth: true,
    permission: 'payment.write',
    idempotent: true,
    body: JSON.stringify({
      invoiceId: 'RUPSA-INV-000457',
      amount: 100000,
      currency: 'RWF',
      paymentChannel: 'BANK',
      payerReference: 'PARENT-001',
      originCountry: 'RW',
      destinationCountry: 'RW',
    }, null, 2),
  },
  {
    id: 'payments-list',
    group: 'Payments',
    method: 'GET',
    path: '/api/v1/payments',
    title: 'List payments',
    description: 'List payment intents, optionally for one invoice.',
    auth: true,
    permission: 'payment.read',
    queryParams: [{ name: 'invoiceId', example: 'RUPSA-INV-000457', description: 'Optional invoice filter' }],
  },
  {
    id: 'payments-get',
    group: 'Payments',
    method: 'GET',
    path: '/api/v1/payments/:paymentId',
    title: 'Payment status',
    description: 'Current payment state and settlement reference once the rail confirms.',
    auth: true,
    permission: 'payment.read',
    pathParams: [{ name: 'paymentId', example: 'RUPSA-PAY-000790', description: 'Public payment ID' }],
  },
  {
    id: 'payments-rails',
    group: 'Payments',
    method: 'GET',
    path: '/api/v1/payments/rails',
    title: 'Approved payment rails',
    description: 'Bank, PSP, mobile money and card rails UPSA Next Payment may route to. Licensed institutions still move the funds.',
    auth: true,
    permission: 'payment.read',
  },
  {
    id: 'payments-corridors',
    group: 'Payments',
    method: 'GET',
    path: '/api/v1/payments/corridors',
    title: 'EAC corridors',
    description: 'Rwanda (RSwitch) ↔ Tanzania (TIPS) is the pilot. Uganda, Kenya, Burundi, South Sudan and DRC are planned.',
    auth: true,
    permission: 'payment.read',
  },
  {
    id: 'payments-events',
    group: 'Payments',
    method: 'GET',
    path: '/api/v1/payments/events',
    title: 'Payment event bus',
    description: 'Recent PAYMENT.INITIATED, PAYMENT.SUCCESS, PAYMENT.FAILED, PAYMENT.REFUNDED and SETTLEMENT.COMPLETED events.',
    auth: true,
    permission: 'payment.read',
  },
  {
    id: 'payments-retry',
    group: 'Payments',
    method: 'POST',
    path: '/api/v1/payments/:paymentId/retry',
    title: 'Retry a failed payment',
    description: 'Switch the instruction to the next approved rail of the same kind. Limited to three attempts.',
    auth: true,
    permission: 'payment.write',
    idempotent: true,
    pathParams: [{ name: 'paymentId', example: 'RUPSA-PAY-000790', description: 'Public payment ID' }],
  },
  {
    id: 'payments-refund',
    group: 'Payments',
    method: 'POST',
    path: '/api/v1/payments/:paymentId/refund',
    title: 'Refund a payment',
    description: 'PAY-06. Unwinds the school ledger and publishes PAYMENT.REFUNDED.',
    auth: true,
    permission: 'payment.write',
    idempotent: true,
    pathParams: [{ name: 'paymentId', example: 'RUPSA-PAY-000790', description: 'Public payment ID' }],
  },
  {
    id: 'webhooks-payment',
    group: 'Webhooks',
    method: 'POST',
    path: '/api/v1/webhooks/payment',
    title: 'Payment webhook',
    description: 'Bank or PSP callback. Replay-protected by eventId, timestamp window and idempotency.',
    auth: false,
    idempotent: true,
    body: JSON.stringify({
      event: 'PAYMENT.SUCCESS',
      eventId: 'EVT-DEV-0001',
      paymentId: 'RUPSA-PAY-000790',
      invoiceId: 'RUPSA-INV-000457',
      amount: 100000,
      currency: 'RWF',
      transactionReference: 'BANK-REF-123456',
      timestamp: new Date().toISOString(),
    }, null, 2),
  },
  {
    id: 'settlements-create',
    group: 'Settlements',
    method: 'POST',
    path: '/api/v1/settlements',
    title: 'Record settlement',
    description: 'PAY-08. Record that funds settled to a school. Optional paymentIds links confirmed payments and publishes SETTLEMENT.COMPLETED.',
    auth: true,
    permission: 'payment.write',
    body: JSON.stringify({
      schoolId: 'RUPSA-SCH-000123',
      amount: 100000,
      currency: 'RWF',
      rail: 'BANK',
      reference: 'SET-DEV-0001',
    }, null, 2),
  },
  {
    id: 'settlements-list',
    group: 'Settlements',
    method: 'GET',
    path: '/api/v1/settlements',
    title: 'List settlements',
    description: 'Settlement history for reconciliation.',
    auth: true,
    permission: 'payment.read',
  },
  {
    id: 'reconciliation-list',
    group: 'Reconciliation',
    method: 'GET',
    path: '/api/v1/reconciliation',
    title: 'Reconciliation book',
    description: 'Match invoice + payment + settlement. Statuses include MATCHED, UNMATCHED and UNDER_REVIEW.',
    auth: true,
    permission: 'payment.read',
    queryParams: [{ name: 'status', example: 'MATCHED', description: 'Optional reconciliation status' }],
  },
  {
    id: 'consents-create',
    group: 'Consents',
    method: 'POST',
    path: '/api/v1/consents',
    title: 'Grant consent',
    description: 'First-class consent before sharing a financial profile with an institution.',
    auth: true,
    permission: 'consent.write',
    body: JSON.stringify({
      subjectId: 'RUPSA-SCH-000123',
      purpose: 'CREDIT_ASSESSMENT',
      recipient: 'FI-001',
      scope: ['FINANCIAL_PROFILE', 'PAYMENT_HISTORY', 'LOAN_HISTORY'],
      expiresAt: '2027-09-21',
    }, null, 2),
  },
  {
    id: 'consents-list',
    group: 'Consents',
    method: 'GET',
    path: '/api/v1/consents',
    title: 'List consents',
    description: 'Consent register for a subject.',
    auth: true,
    permission: 'consent.read',
    queryParams: [{ name: 'subjectId', example: 'RUPSA-SCH-000123', description: 'School or subject public ID' }],
  },
  {
    id: 'consents-withdraw',
    group: 'Consents',
    method: 'POST',
    path: '/api/v1/consents/:consentId/withdraw',
    title: 'Withdraw consent',
    description: 'Revoke a previously granted consent.',
    auth: true,
    permission: 'consent.write',
    pathParams: [{ name: 'consentId', example: 'RUPSA-CON-000001', description: 'Public consent ID' }],
  },
  {
    id: 'loans-apply',
    group: 'Loans',
    method: 'POST',
    path: '/api/v1/loan-applications',
    title: 'Create loan application',
    description: 'Submit a financing request. The licensed institution keeps the credit decision.',
    auth: true,
    permission: 'loan.write',
    body: JSON.stringify({
      schoolId: 'RUPSA-SCH-000123',
      financialInstitutionId: 'FI-001',
      productCode: 'WORKING_CAPITAL',
      requestedAmount: 50000000,
      currency: 'RWF',
      tenorMonths: 24,
      purpose: 'School expansion',
      guaranteeRequested: true,
      guaranteeAmountRequested: 20000000,
    }, null, 2),
  },
  {
    id: 'loans-apps',
    group: 'Loans',
    method: 'GET',
    path: '/api/v1/loan-applications',
    title: 'List applications',
    description: 'Loan application pipeline for a school or the full sandbox book.',
    auth: true,
    permission: 'loan.read',
    queryParams: [{ name: 'schoolId', example: 'RUPSA-SCH-000123', description: 'Optional school filter' }],
  },
  {
    id: 'loans-assess',
    group: 'Loans',
    method: 'POST',
    path: '/api/v1/loan-applications/:applicationId/assessment',
    title: 'Run assessment',
    description: 'UPSA Next Payment analytical assessment only. Final decision remains with the FI.',
    auth: true,
    permission: 'loan.write',
    pathParams: [{ name: 'applicationId', example: 'RUPSA-LA-000124', description: 'Application public ID' }],
  },
  {
    id: 'loans-decide',
    group: 'Loans',
    method: 'POST',
    path: '/api/v1/loan-applications/:applicationId/decision',
    title: 'Credit decision',
    description: 'Institution decision: APPROVED, DECLINED, CONDITIONAL_APPROVAL, MORE_INFORMATION_REQUIRED or CANCELLED.',
    auth: true,
    permission: 'loan.write',
    pathParams: [{ name: 'applicationId', example: 'RUPSA-LA-000124', description: 'Application public ID' }],
    body: JSON.stringify({
      decision: 'APPROVED',
      approvedAmount: 45000000,
      currency: 'RWF',
      tenorMonths: 24,
      interestRate: 12.5,
      decisionReference: 'FI-CREDIT-123456',
    }, null, 2),
  },
  {
    id: 'loans-get',
    group: 'Loans',
    method: 'GET',
    path: '/api/v1/loans/:loanId',
    title: 'Retrieve loan',
    description: 'Loan contract created after an approved decision.',
    auth: true,
    permission: 'loan.read',
    pathParams: [{ name: 'loanId', example: 'RUPSA-LOAN-000124', description: 'Public loan ID' }],
  },
  {
    id: 'loans-balance',
    group: 'Loans',
    method: 'GET',
    path: '/api/v1/loans/:loanId/balance',
    title: 'Loan balance',
    description: 'Principal, interest, fees and total outstanding.',
    auth: true,
    permission: 'loan.read',
    pathParams: [{ name: 'loanId', example: 'RUPSA-LOAN-000124', description: 'Public loan ID' }],
  },
  {
    id: 'loans-disburse',
    group: 'Loans',
    method: 'POST',
    path: '/api/v1/loans/:loanId/disbursement',
    title: 'Disburse loan',
    description: 'Record an FI disbursement. Requires Idempotency-Key.',
    auth: true,
    permission: 'loan.write',
    idempotent: true,
    pathParams: [{ name: 'loanId', example: 'RUPSA-LOAN-000124', description: 'Public loan ID' }],
    body: JSON.stringify({
      amount: 45000000,
      currency: 'RWF',
      disbursementAccount: 'ACCOUNT-REFERENCE',
      transactionReference: 'FI-DISB-DEV-1',
    }, null, 2),
  },
  {
    id: 'loans-repay',
    group: 'Loans',
    method: 'POST',
    path: '/api/v1/loans/:loanId/repayments',
    title: 'Post repayment',
    description: 'Post a loan repayment against outstanding principal. Requires Idempotency-Key.',
    auth: true,
    permission: 'loan.write',
    idempotent: true,
    pathParams: [{ name: 'loanId', example: 'RUPSA-LOAN-000124', description: 'Public loan ID' }],
    body: JSON.stringify({
      amount: 2500000,
      currency: 'RWF',
      paymentReference: 'PAY-DEV-123456',
      paymentDate: '2026-09-21',
    }, null, 2),
  },
  {
    id: 'guarantees-create',
    group: 'Guarantees',
    method: 'POST',
    path: '/api/v1/guarantees',
    title: 'Request guarantee',
    description: 'Request cover from the RUPSA guarantee facility. Requires Idempotency-Key.',
    auth: true,
    permission: 'guarantee.write',
    idempotent: true,
    body: JSON.stringify({
      loanApplicationId: 'RUPSA-LA-000124',
      schoolId: 'RUPSA-SCH-000123',
      financialInstitutionId: 'FI-001',
      loanAmount: 50000000,
      guaranteeAmount: 20000000,
      currency: 'RWF',
    }, null, 2),
  },
  {
    id: 'guarantees-list',
    group: 'Guarantees',
    method: 'GET',
    path: '/api/v1/guarantees',
    title: 'List guarantees',
    description: 'Guarantee register plus live facility exposure.',
    auth: true,
    permission: 'guarantee.read',
  },
  {
    id: 'guarantees-decide',
    group: 'Guarantees',
    method: 'POST',
    path: '/api/v1/guarantees/:guaranteeId/decision',
    title: 'Guarantee decision',
    description: 'Approve or decline. Approved cover reduces available facility capacity.',
    auth: true,
    permission: 'guarantee.write',
    idempotent: true,
    pathParams: [{ name: 'guaranteeId', example: 'RUPSA-GUA-000001', description: 'Public guarantee ID' }],
    body: JSON.stringify({
      decision: 'APPROVED',
      guaranteedAmount: 20000000,
      expiryDate: '2028-09-21',
    }, null, 2),
  },
  {
    id: 'guarantees-claim',
    group: 'Guarantees',
    method: 'POST',
    path: '/api/v1/guarantees/:guaranteeId/claims',
    title: 'File claim',
    description: 'File a qualifying-default claim against an active guarantee.',
    auth: true,
    permission: 'guarantee.write',
    idempotent: true,
    pathParams: [{ name: 'guaranteeId', example: 'RUPSA-GUA-000001', description: 'Public guarantee ID' }],
    body: JSON.stringify({
      loanId: 'RUPSA-LOAN-000124',
      claimAmount: 15000000,
      reason: 'QUALIFYING_DEFAULT',
      supportingReference: 'RECOVERY-123',
    }, null, 2),
  },
  {
    id: 'notifications-create',
    group: 'Notifications',
    method: 'POST',
    path: '/api/v1/notifications',
    title: 'Queue notification',
    description: 'Queue an email, SMS or in-app notice. Accepted asynchronously.',
    auth: true,
    permission: 'admin.write',
    body: JSON.stringify({
      channel: 'EMAIL',
      subject: 'Fee receipt',
      body: 'Your payment of 100,000 RWF has been received.',
    }, null, 2),
  },
  {
    id: 'notifications-list',
    group: 'Notifications',
    method: 'GET',
    path: '/api/v1/notifications',
    title: 'List notifications',
    description: 'Recent notification queue.',
    auth: true,
    permission: 'report.read',
  },
  {
    id: 'reports-overview',
    group: 'Reports',
    method: 'GET',
    path: '/api/v1/reports/overview',
    title: 'Platform overview',
    description: 'Collections, credit book and guarantee exposure in one payload.',
    auth: true,
    permission: 'report.read',
  },
  {
    id: 'donations-summary',
    group: 'Donations',
    method: 'GET',
    path: '/api/v1/donations/summary',
    title: 'Donation dashboard',
    description: 'Totals for received, pending, allocated, distributed, and refunded donations.',
    auth: true,
    permission: 'donation.read',
  },
  {
    id: 'donations-donor',
    group: 'Donations',
    method: 'POST',
    path: '/api/v1/donations/donors',
    title: 'Register donor',
    description: 'Save a draft or register a donor. Organisation name, registration number, and tax ID are required for companies, foundations, institutions, and partners.',
    auth: true,
    permission: 'donation.write',
    body: JSON.stringify({
      donorType: 'INDIVIDUAL',
      name: 'Aline Mukamana',
      country: 'Rwanda',
      address: 'Kigali',
      telephone: '0788000000',
      mode: 'register',
    }, null, 2),
  },
  {
    id: 'donations-payment',
    group: 'Donations',
    method: 'POST',
    path: '/api/v1/donations/:donationId/payments',
    title: 'Process donation payment',
    description: 'Send a verified monetary donation through the payment service. Idempotency-Key is required.',
    auth: true,
    permission: 'donation.write',
    idempotent: true,
    pathParams: [{ name: 'donationId', example: 'RUPSA-DON-000001', description: 'Donation reference' }],
    body: JSON.stringify({ paymentMethod: 'MOBILE_PAYMENT', payerName: 'Aline Mukamana' }, null, 2),
  },
  {
    id: 'investments-summary',
    group: 'Investments',
    method: 'GET',
    path: '/api/v1/investments/summary',
    title: 'Investment dashboard',
    description: 'Portfolio value, invested amount, open applications, and realized returns from the investment ledger.',
    auth: true,
    permission: 'investment.read',
  },
  {
    id: 'investments-opportunity',
    group: 'Investments',
    method: 'POST',
    path: '/api/v1/investments/opportunities',
    title: 'Create opportunity',
    description: 'Save an investment opportunity. Publishing requires the proposal documents and uses the status action.',
    auth: true,
    permission: 'investment.write',
    body: JSON.stringify({
      code: 'EDU-2026',
      name: 'School infrastructure note',
      investmentType: 'DEBT',
      description: 'A member note for school infrastructure.',
      projectName: 'Classroom block',
      sector: 'EDUCATION',
      location: 'Kigali',
      managerName: 'RUPSA Capital',
      startDate: '2026-10-03',
      endDate: '2027-10-03',
      targetAmount: 1000000,
      minimumAmount: 50000,
      currency: 'RWF',
      expectedReturnRate: 8,
      returnFrequency: 'ANNUAL',
      investmentPeriod: '12 months',
      riskDisclosure: 'Capital is at risk.',
    }, null, 2),
  },
  {
    id: 'investments-contribution',
    group: 'Investments',
    method: 'POST',
    path: '/api/v1/investments/positions/:positionId/payments',
    title: 'Record contribution',
    description: 'Send a bank or mobile contribution through the payment service. Allocation posts to the investment ledger only after a matched confirmation.',
    auth: true,
    permission: 'investment.write',
    idempotent: true,
    pathParams: [{ name: 'positionId', example: 'RUPSA-IVT-000001', description: 'Investment reference' }],
    body: JSON.stringify({ amount: 50000, contributionDate: '2026-10-03', paymentMethod: 'MOBILE_PAYMENT' }, null, 2),
  },
  {
    id: 'accounts-summary',
    group: 'Accounts',
    method: 'GET',
    path: '/api/v1/accounts/summary',
    title: 'Account opening dashboard',
    description: 'Counts of applications in review and opened accounts by type. An active account with no activity for 180 days is marked dormant.',
    auth: true,
    permission: 'account.read',
  },
  {
    id: 'accounts-open',
    group: 'Accounts',
    method: 'POST',
    path: '/api/v1/accounts',
    title: 'Open an account application',
    description: 'Submit a school, parent, student, teacher, or supplier application. Pass partyId to link an existing school, guardian, student, or registration.',
    auth: true,
    permission: 'account.write',
    body: JSON.stringify({
      mode: 'submit',
      accountType: 'PARENT',
      channel: 'BRANCH',
      purpose: 'School fees',
      applicantName: 'Aline Mukamana',
      identityNumber: '1199080012345678',
      phone: '+250788000111',
      email: 'aline@example.rw',
      province: 'Kigali',
      district: 'Gasabo',
      address: 'Kacyiru',
      termsAccepted: true,
      privacyAccepted: true,
      dataConsent: true,
      profile: { relationship: 'Parent' },
      documents: [{ documentType: 'NATIONAL_ID', fileName: 'aline-id.pdf' }],
    }, null, 2),
  },
  {
    id: 'accounts-activate',
    group: 'Accounts',
    method: 'POST',
    path: '/api/v1/accounts/:accountId/activation',
    title: 'Activate an approved account',
    description: 'Creates or updates the linked school, guardian, student, or registration, records the role and verification method, and queues the welcome notice.',
    auth: true,
    permission: 'account.write',
    pathParams: [{ name: 'accountId', example: 'RUPSA-ACC-000001', description: 'Account application reference' }],
    body: JSON.stringify({ username: 'aline.mukamana', mfaMethod: 'SMS', dailyLimit: 500000, transactionLimit: 200000 }, null, 2),
  },
  {
    id: 'literacy-summary',
    group: 'Financial literacy',
    method: 'GET',
    path: '/api/v1/literacy/summary',
    title: 'Training dashboard',
    description: 'Learners, open courses, completion, attendance, pass rate, and certificates. Calculators on this module are illustrations and do not post money.',
    auth: true,
    permission: 'literacy.read',
  },
  {
    id: 'literacy-enrol',
    group: 'Financial literacy',
    method: 'POST',
    path: '/api/v1/literacy/enrollments',
    title: 'Enrol a learner',
    description: 'Enrols an existing school, parent, student, or registration on a published course. A certificate is issued only after the post-assessment is passed.',
    auth: true,
    permission: 'literacy.write',
    body: JSON.stringify({ learnerId: 'RUPSA-LLN-000001', courseId: 'RUPSA-LCR-000001', deliveryMethod: 'CLASSROOM', startDate: '2026-10-03' }, null, 2),
  },
]

export function endpointById(id: string) {
  return endpoints.find((item) => item.id === id) ?? endpoints[0]
}

export function resolvePath(path: string, params: Record<string, string>) {
  return path.replace(/:([A-Za-z]+)/g, (_, key: string) => encodeURIComponent(params[key] || `:${key}`))
}
